// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: TouchPanel

#ifndef _TOUCHPANEL_UI_H
#define _TOUCHPANEL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "dataStruct.h"

///////////////////// SCREENS ////////////////////

#include "ui_Page1.h"
#include "ui_Page2.h"

///////////////////// VARIABLES ////////////////////
extern bool blnTouched;

//extern bool blnButton1;
//extern bool blnButton2;
//extern bool blnButton3;
//extern bool blnButton4;
//extern bool blnButton5;
//extern bool blnButton6;

//extern struct txData;
//extern struct rxData;
//extern struct currentData;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_Font16);
LV_FONT_DECLARE(ui_font_Font20);
LV_FONT_DECLARE(ui_font_Font34);
LV_FONT_DECLARE(ui_font_Font38);
LV_FONT_DECLARE(ui_font_Font50);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
