// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: TouchPanel

#ifndef UI_PAGE2_H
#define UI_PAGE2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Page2
extern void ui_Page2_screen_init(void);
extern void ui_Page2_screen_destroy(void);
extern lv_obj_t * ui_Page2;
extern void ui_event_Page1Button(lv_event_t * e);
extern lv_obj_t * ui_Page1Button;
extern lv_obj_t * ui_Page1ButtonLabel;
extern lv_obj_t * ui_DebugLog;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

