// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: TouchPanel

#include "ui.h"

lv_obj_t * ui_Page1 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Button1Value = NULL;
lv_obj_t * ui_Button1Label = NULL;
lv_obj_t * ui_Button1Indicator = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Button2Value = NULL;
lv_obj_t * ui_Button2Label = NULL;
lv_obj_t * ui_Button2Indicator = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Button3Value = NULL;
lv_obj_t * ui_Button3Label = NULL;
lv_obj_t * ui_Button3Indicator = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Button4Value = NULL;
lv_obj_t * ui_Button4Label = NULL;
lv_obj_t * ui_Button4Indicator = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Button5Value = NULL;
lv_obj_t * ui_Button5Label = NULL;
lv_obj_t * ui_Button5Indicator = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Button6Value = NULL;
lv_obj_t * ui_Button6Label = NULL;
lv_obj_t * ui_Button6Indicator = NULL;
lv_obj_t * ui_OutTempLabel = NULL;
lv_obj_t * ui_OutTempDisplay = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        Button1(e);
        currentData.Button1State = !currentData.Button1State;
        blnTouched = true;
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        Button2(e);
        currentData.Button2State = !currentData.Button2State;
        blnTouched = true;
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        Button3(e);
        currentData.Button3State = !currentData.Button3State;
        blnTouched = true;
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        Button4(e);
        currentData.Button4State = !currentData.Button4State;
        blnTouched = true;
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        Button5(e);
        currentData.Button5State = !currentData.Button5State;
        blnTouched = true;
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        Button6(e);
        currentData.Button6State = !currentData.Button6State;
        blnTouched = true;
    }
}

// build funtions

void ui_Page1_screen_init(void)
{
    ui_Page1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Page1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Page1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Page1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Page1);
    lv_obj_set_width(ui_Button1, 160);
    lv_obj_set_height(ui_Button1, 220);
    lv_obj_set_x(ui_Button1, -310);
    lv_obj_set_y(ui_Button1, -120);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button1, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1Value = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Button1Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Button1Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Button1Value, 0);
    lv_obj_set_y(ui_Button1Value, -10);
    lv_obj_set_align(ui_Button1Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Button1Value, "");
    lv_obj_set_style_text_color(ui_Button1Value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button1Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Button1Value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Button1Value, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button1Value, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1Label = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Button1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Button1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Button1Label, 0);
    lv_obj_set_y(ui_Button1Label, 55);
    lv_obj_set_align(ui_Button1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Button1Label, "");
    lv_obj_set_style_text_color(ui_Button1Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button1Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Button1Label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Button1Label, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button1Label, &ui_font_Font34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1Indicator = lv_obj_create(ui_Button1);
    lv_obj_set_width(ui_Button1Indicator, 100);
    lv_obj_set_height(ui_Button1Indicator, 40);
    lv_obj_set_x(ui_Button1Indicator, 0);
    lv_obj_set_y(ui_Button1Indicator, -65);
    lv_obj_set_align(ui_Button1Indicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button1Indicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1Indicator, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1Indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button1Indicator, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button1Indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button1Indicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_Page1);
    lv_obj_set_width(ui_Button2, 160);
    lv_obj_set_height(ui_Button2, 220);
    lv_obj_set_x(ui_Button2, -135);
    lv_obj_set_y(ui_Button2, -120);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button2, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2Value = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Button2Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Button2Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Button2Value, 0);
    lv_obj_set_y(ui_Button2Value, -10);
    lv_obj_set_align(ui_Button2Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Button2Value, "");
    lv_obj_set_style_text_color(ui_Button2Value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button2Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Button2Value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Button2Value, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button2Value, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2Label = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Button2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Button2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Button2Label, 0);
    lv_obj_set_y(ui_Button2Label, 55);
    lv_obj_set_align(ui_Button2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Button2Label, "");
    lv_obj_set_style_text_color(ui_Button2Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button2Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Button2Label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Button2Label, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button2Label, &ui_font_Font34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2Indicator = lv_obj_create(ui_Button2);
    lv_obj_set_width(ui_Button2Indicator, 100);
    lv_obj_set_height(ui_Button2Indicator, 40);
    lv_obj_set_x(ui_Button2Indicator, 0);
    lv_obj_set_y(ui_Button2Indicator, -65);
    lv_obj_set_align(ui_Button2Indicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button2Indicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2Indicator, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2Indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button2Indicator, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button2Indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button2Indicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Page1);
    lv_obj_set_width(ui_Button3, 160);
    lv_obj_set_height(ui_Button3, 220);
    lv_obj_set_x(ui_Button3, 40);
    lv_obj_set_y(ui_Button3, -120);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button3, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3Value = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Button3Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Button3Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Button3Value, 0);
    lv_obj_set_y(ui_Button3Value, -10);
    lv_obj_set_align(ui_Button3Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Button3Value, "");
    lv_obj_set_style_text_color(ui_Button3Value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button3Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Button3Value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Button3Value, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button3Value, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3Label = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Button3Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Button3Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Button3Label, 0);
    lv_obj_set_y(ui_Button3Label, 55);
    lv_obj_set_align(ui_Button3Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Button3Label, "");
    lv_obj_set_style_text_color(ui_Button3Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button3Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Button3Label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Button3Label, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button3Label, &ui_font_Font34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3Indicator = lv_obj_create(ui_Button3);
    lv_obj_set_width(ui_Button3Indicator, 100);
    lv_obj_set_height(ui_Button3Indicator, 40);
    lv_obj_set_x(ui_Button3Indicator, 0);
    lv_obj_set_y(ui_Button3Indicator, -65);
    lv_obj_set_align(ui_Button3Indicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button3Indicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3Indicator, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3Indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button3Indicator, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button3Indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button3Indicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_Page1);
    lv_obj_set_width(ui_Button4, 160);
    lv_obj_set_height(ui_Button4, 220);
    lv_obj_set_x(ui_Button4, -310);
    lv_obj_set_y(ui_Button4, 115);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button4, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4Value = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Button4Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Button4Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Button4Value, 0);
    lv_obj_set_y(ui_Button4Value, -10);
    lv_obj_set_align(ui_Button4Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Button4Value, "");
    lv_obj_set_style_text_color(ui_Button4Value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button4Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Button4Value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Button4Value, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button4Value, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4Label = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Button4Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Button4Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Button4Label, 0);
    lv_obj_set_y(ui_Button4Label, 55);
    lv_obj_set_align(ui_Button4Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Button4Label, "");
    lv_obj_set_style_text_color(ui_Button4Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button4Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Button4Label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Button4Label, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button4Label, &ui_font_Font34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4Indicator = lv_obj_create(ui_Button4);
    lv_obj_set_width(ui_Button4Indicator, 100);
    lv_obj_set_height(ui_Button4Indicator, 40);
    lv_obj_set_x(ui_Button4Indicator, 0);
    lv_obj_set_y(ui_Button4Indicator, -65);
    lv_obj_set_align(ui_Button4Indicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button4Indicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4Indicator, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4Indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button4Indicator, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button4Indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button4Indicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_Page1);
    lv_obj_set_width(ui_Button5, 160);
    lv_obj_set_height(ui_Button5, 220);
    lv_obj_set_x(ui_Button5, -135);
    lv_obj_set_y(ui_Button5, 115);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button5, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5Value = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Button5Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Button5Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Button5Value, 0);
    lv_obj_set_y(ui_Button5Value, -10);
    lv_obj_set_align(ui_Button5Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Button5Value, "");
    lv_obj_set_style_text_color(ui_Button5Value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button5Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Button5Value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Button5Value, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button5Value, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5Label = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Button5Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Button5Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Button5Label, 0);
    lv_obj_set_y(ui_Button5Label, 55);
    lv_obj_set_align(ui_Button5Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Button5Label, "");
    lv_obj_set_style_text_color(ui_Button5Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button5Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Button5Label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Button5Label, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button5Label, &ui_font_Font34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5Indicator = lv_obj_create(ui_Button5);
    lv_obj_set_width(ui_Button5Indicator, 100);
    lv_obj_set_height(ui_Button5Indicator, 40);
    lv_obj_set_x(ui_Button5Indicator, 0);
    lv_obj_set_y(ui_Button5Indicator, -65);
    lv_obj_set_align(ui_Button5Indicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button5Indicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button5Indicator, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5Indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button5Indicator, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button5Indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button5Indicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_Page1);
    lv_obj_set_width(ui_Button6, 160);
    lv_obj_set_height(ui_Button6, 220);
    lv_obj_set_x(ui_Button6, 40);
    lv_obj_set_y(ui_Button6, 115);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button6, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button6, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6Value = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Button6Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Button6Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Button6Value, 0);
    lv_obj_set_y(ui_Button6Value, -10);
    lv_obj_set_align(ui_Button6Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Button6Value, "");
    lv_obj_set_style_text_color(ui_Button6Value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button6Value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Button6Value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Button6Value, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button6Value, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6Label = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Button6Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Button6Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Button6Label, 0);
    lv_obj_set_y(ui_Button6Label, 55);
    lv_obj_set_align(ui_Button6Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Button6Label, "");
    lv_obj_set_style_text_color(ui_Button6Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button6Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Button6Label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Button6Label, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button6Label, &ui_font_Font34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6Indicator = lv_obj_create(ui_Button6);
    lv_obj_set_width(ui_Button6Indicator, 100);
    lv_obj_set_height(ui_Button6Indicator, 40);
    lv_obj_set_x(ui_Button6Indicator, 0);
    lv_obj_set_y(ui_Button6Indicator, -65);
    lv_obj_set_align(ui_Button6Indicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button6Indicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button6Indicator, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6Indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button6Indicator, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button6Indicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button6Indicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OutTempLabel = lv_label_create(ui_Page1);
    lv_obj_set_width(ui_OutTempLabel, 154);
    lv_obj_set_height(ui_OutTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OutTempLabel, 260);
    lv_obj_set_y(ui_OutTempLabel, -185);
    lv_obj_set_align(ui_OutTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OutTempLabel, "Outside");
    lv_obj_set_style_text_color(ui_OutTempLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OutTempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_OutTempLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OutTempLabel, &ui_font_Font38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OutTempDisplay = lv_label_create(ui_OutTempLabel);
    lv_obj_set_width(ui_OutTempDisplay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OutTempDisplay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OutTempDisplay, 0);
    lv_obj_set_y(ui_OutTempDisplay, 45);
    lv_obj_set_align(ui_OutTempDisplay, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_OutTempDisplay, "100°");
    lv_obj_set_style_text_color(ui_OutTempDisplay, lv_color_hex(0xFFFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OutTempDisplay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_OutTempDisplay, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OutTempDisplay, &ui_font_Font38, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);

}

void ui_Page1_screen_destroy(void)
{
    if(ui_Page1) lv_obj_del(ui_Page1);

    // NULL screen variables
    ui_Page1 = NULL;
    ui_Button1 = NULL;
    ui_Button1Value = NULL;
    ui_Button1Label = NULL;
    ui_Button1Indicator = NULL;
    ui_Button2 = NULL;
    ui_Button2Value = NULL;
    ui_Button2Label = NULL;
    ui_Button2Indicator = NULL;
    ui_Button3 = NULL;
    ui_Button3Value = NULL;
    ui_Button3Label = NULL;
    ui_Button3Indicator = NULL;
    ui_Button4 = NULL;
    ui_Button4Value = NULL;
    ui_Button4Label = NULL;
    ui_Button4Indicator = NULL;
    ui_Button5 = NULL;
    ui_Button5Value = NULL;
    ui_Button5Label = NULL;
    ui_Button5Indicator = NULL;
    ui_Button6 = NULL;
    ui_Button6Value = NULL;
    ui_Button6Label = NULL;
    ui_Button6Indicator = NULL;
    ui_OutTempLabel = NULL;
    ui_OutTempDisplay = NULL;

}
