// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: TouchPanel

#include "ui.h"

lv_obj_t * ui_Page2 = NULL;
lv_obj_t * ui_Page1Button = NULL;
lv_obj_t * ui_Page1ButtonLabel = NULL;
lv_obj_t * ui_DebugLog = NULL;
// event funtions
void ui_event_Page1Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Page1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Page1_screen_init);
    }
}

// build funtions

void ui_Page2_screen_init(void)
{
    ui_Page2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Page2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Page2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Page2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Page1Button = lv_btn_create(ui_Page2);
    lv_obj_set_width(ui_Page1Button, 160);
    lv_obj_set_height(ui_Page1Button, 58);
    lv_obj_set_x(ui_Page1Button, -309);
    lv_obj_set_y(ui_Page1Button, 197);
    lv_obj_set_align(ui_Page1Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Page1Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Page1Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Page1Button, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Page1Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Page1Button, lv_color_hex(0x3E3E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Page1Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Page1Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Page1ButtonLabel = lv_label_create(ui_Page1Button);
    lv_obj_set_width(ui_Page1ButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Page1ButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Page1ButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Page1ButtonLabel, "<- Page");
    lv_obj_set_style_text_color(ui_Page1ButtonLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Page1ButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Page1ButtonLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Page1ButtonLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Page1ButtonLabel, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DebugLog = lv_textarea_create(ui_Page2);
    lv_obj_set_width(ui_DebugLog, 250);
    lv_obj_set_height(ui_DebugLog, 460);
    lv_obj_set_x(ui_DebugLog, 260);
    lv_obj_set_y(ui_DebugLog, 0);
    lv_obj_set_align(ui_DebugLog, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_DebugLog, "Debug Window");
    lv_textarea_set_placeholder_text(ui_DebugLog, "Placeholder...");
    lv_obj_clear_flag(ui_DebugLog, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_DebugLog, lv_color_hex(0x822828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DebugLog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DebugLog, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DebugLog, lv_color_hex(0x030202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DebugLog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DebugLog, lv_color_hex(0x3A3838), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DebugLog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Page1Button, ui_event_Page1Button, LV_EVENT_ALL, NULL);

}

void ui_Page2_screen_destroy(void)
{
    if(ui_Page2) lv_obj_del(ui_Page2);

    // NULL screen variables
    ui_Page2 = NULL;
    ui_Page1Button = NULL;
    ui_Page1ButtonLabel = NULL;
    ui_DebugLog = NULL;

}
