// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: TouchPanel

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Button1(lv_event_t * e);
void Button2(lv_event_t * e);
void Button3(lv_event_t * e);
void Button4(lv_event_t * e);
void Button5(lv_event_t * e);
void Button6(lv_event_t * e);
void brightness(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
