// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: TouchPanel

#ifndef UI_PAGE1_H
#define UI_PAGE1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Page1
extern void ui_Page1_screen_init(void);
extern void ui_Page1_screen_destroy(void);
extern lv_obj_t * ui_Page1;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button1Label;
extern lv_obj_t * ui_Button1Indicator;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Button2Label;
extern lv_obj_t * ui_Button2Indicator;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Button3Label;
extern lv_obj_t * ui_Button3Indicator;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Button4Label;
extern lv_obj_t * ui_Button4Indicator;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Button5Label;
extern lv_obj_t * ui_Button5Indicator;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Button6Label;
extern lv_obj_t * ui_Button6Indicator;
extern void ui_event_Page2Button(lv_event_t * e);
extern lv_obj_t * ui_Page2Button;
extern lv_obj_t * ui_Page2ButtonLabel;
extern lv_obj_t * ui_OutTempGauge;
extern lv_obj_t * ui_OutTempLabel;
extern lv_obj_t * ui_OutTempDisplay;
extern lv_obj_t * ui_AirPressureGauge;
extern lv_obj_t * ui_AirPressureLabel;
extern lv_obj_t * ui_AirPressureDisplay;
extern lv_obj_t * ui_AirPressureLabel1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

