// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: TouchPanel

#include "ui.h"

void Button1(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	CurrentData.Button1 = !CurrentData.Button1;
	
	if(CurrentData.Button1){
      lv_obj_set_style_bg_color(ui_Button1Indicator,lv_color_hex(0x00FF00),LV_PART_MAIN);
    }
    else{
      lv_obj_set_style_bg_color(ui_Button1Indicator,lv_color_hex(0xFF0000),LV_PART_MAIN);
    }
}

void Button2(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	CurrentData.Button2 = !CurrentData.Button2;
	
	if(CurrentData.Button2){
      lv_obj_set_style_bg_color(ui_Button2Indicator,lv_color_hex(0x00FF00),LV_PART_MAIN);
    }
    else{
      lv_obj_set_style_bg_color(ui_Button2Indicator,lv_color_hex(0xFF0000),LV_PART_MAIN);
    }
}

void Button3(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	CurrentData.Button3 = !CurrentData.Button3;
	
	if(CurrentData.Button3){
      lv_obj_set_style_bg_color(ui_Button3Indicator,lv_color_hex(0x00FF00),LV_PART_MAIN);
    }
    else{
      lv_obj_set_style_bg_color(ui_Button3Indicator,lv_color_hex(0xFF0000),LV_PART_MAIN);
    }
}

void Button4(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	CurrentData.Button4 = !CurrentData.Button4;
	
	if(CurrentData.Button4){
      lv_obj_set_style_bg_color(ui_Button4Indicator,lv_color_hex(0x00FF00),LV_PART_MAIN);
    }
    else{
      lv_obj_set_style_bg_color(ui_Button4Indicator,lv_color_hex(0xFF0000),LV_PART_MAIN);
    }
}

void Button5(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	CurrentData.Button5 = !CurrentData.Button5;
	
	if(CurrentData.Button5){
      lv_obj_set_style_bg_color(ui_Button5Indicator,lv_color_hex(0x00FF00),LV_PART_MAIN);
    }
    else{
      lv_obj_set_style_bg_color(ui_Button5Indicator,lv_color_hex(0xFF0000),LV_PART_MAIN);
    }
}

void Button6(lv_event_t * e)
{
	lv_event_code_t event_code = lv_event_get_code(e);
	CurrentData.Button6 = !CurrentData.Button6;
	
	if(CurrentData.Button6){
      lv_obj_set_style_bg_color(ui_Button6Indicator,lv_color_hex(0x00FF00),LV_PART_MAIN);
    }
    else{
      lv_obj_set_style_bg_color(ui_Button6Indicator,lv_color_hex(0xFF0000),LV_PART_MAIN);
    }
}
void brightness(lv_event_t * e)
{
  analogWrite(2, lv_slider_get_value(ui_BrightnessSlider));
}